import { z } from "zod"

export const alunoFormSchema = z.object({
  nome_completo: z.string().min(1, "Nome completo é obrigatório").max(200),
  data_nascimento: z.string().min(1, "Data de nascimento é obrigatória"),
  sexo: z.string().max(20).nullable().optional(),
  naturalidade: z.string().max(100).nullable().optional(),
  cpf: z.string().max(14).nullable().optional(),
  rg: z.string().max(20).nullable().optional(),
  certidao_nascimento_numero: z.string().max(50).nullable().optional(),
  certidao_livro: z.string().max(20).nullable().optional(),
  certidao_folha: z.string().max(10).nullable().optional(),
  certidao_data_emissao: z.string().nullable().optional().transform((v) => (v === "" ? null : v)),
  certidao_cartorio: z.string().max(100).nullable().optional(),
  certidao_uf: z.string().max(2).nullable().optional(),
  endereco: z.string().max(300).nullable().optional(),
  endereco_numero: z.string().max(20).nullable().optional(),
  bairro: z.string().max(100).nullable().optional(),
  cidade: z.string().max(100).nullable().optional(),
  uf: z.string().max(2).nullable().optional(),
  cep: z.string().max(10).nullable().optional(),
  telefone_residencial: z.string().max(20).nullable().optional(),
  telefone_comercial: z.string().max(20).nullable().optional(),
  telefone: z.string().max(20).nullable().optional(),
  email: z.string().email().nullable().optional().or(z.literal("")),
  nome_mae: z.string().max(200).nullable().optional(),
  profissao_mae: z.string().max(100).nullable().optional(),
  celular_mae: z.string().max(20).nullable().optional(),
  nome_pai: z.string().max(200).nullable().optional(),
  profissao_pai: z.string().max(100).nullable().optional(),
  celular_pai: z.string().max(20).nullable().optional(),
  nome_responsavel: z.string().max(200).nullable().optional(),
  telefone_responsavel: z.string().max(20).nullable().optional(),
  email_responsavel: z.string().email().nullable().optional().or(z.literal("")),
  resp_fin_nome: z.string().max(200).nullable().optional(),
  resp_fin_data_nascimento: z.string().nullable().optional().transform((v) => (v === "" ? null : v)),
  resp_fin_estado_civil: z.string().max(30).nullable().optional(),
  resp_fin_cpf: z.string().max(14).nullable().optional(),
  resp_fin_identidade: z.string().max(30).nullable().optional(),
  resp_fin_orgao_emissor: z.string().max(20).nullable().optional(),
  resp_fin_uf: z.string().max(2).nullable().optional(),
  resp_fin_grau_parentesco: z.string().max(50).nullable().optional(),
  resp_fin_endereco: z.string().max(300).nullable().optional(),
  resp_fin_bairro: z.string().max(100).nullable().optional(),
  resp_fin_telefone: z.string().max(20).nullable().optional(),
  resp_fin_cidade: z.string().max(100).nullable().optional(),
  resp_fin_uf_endereco: z.string().max(2).nullable().optional(),
  resp_fin_cep: z.string().max(10).nullable().optional(),
  uso_medicamento_continuo: z.boolean(),
  medicamento_continuo_qual: z.string().max(300).nullable().optional(),
  alergia_medicamento: z.boolean(),
  alergia_medicamento_qual: z.string().max(300).nullable().optional(),
  alergia_alimento: z.boolean(),
  alergia_alimento_qual: z.string().max(300).nullable().optional(),
  periodo_letivo: z.string().max(10).nullable().optional(),
  nivel: z.string().max(50).nullable().optional(),
  turno_preferencial: z.string().max(20).nullable().optional(),
  responsavel_matricula: z.string().max(200).nullable().optional(),
  observacoes: z.string().max(500).nullable().optional(),
  ativo: z.boolean(),
})
